import uuid
from typing import TYPE_CHECKING, Any, NewType

from pydantic import BaseModel

from nexus.actors.s3_client_provider import DEFAULT_S3_CLIENT_PROVIDER, S3ClientProvider
from nexus.core.dsl.nodes import Node, NodeSinks, NodeSources, Sink, SinkName, Source, SourceName
from nexus.core.runtime.actor import Actor, ActorBuilder, EventHandler
from nexus.core.runtime.context_store import Context, ContextStore
from nexus.core.runtime.events import MessagesToSend, PipeToBus, ReceiveEvent, SendEvent

if TYPE_CHECKING:
    from mypy_boto3_s3 import S3Client


class PayloadCreator[Input, ExecutorPayload](Node):
    input: Sink[Input] # consumes attempts generated by retry strategy

    created_payload: Source[ExecutorPayload] # emits the next attempt to execute,
    # with the original input and the generated payload for the executor

    def __init__(self, _id: str) -> None:
        super().__init__(_id)
        self.input = Sink[Input](f"{self.id}-input")
        self.created_payload = Source[ExecutorPayload](f"{self.id}-created-payload")

    def sinks(self) -> NodeSinks:
        return NodeSinks(sinks={SinkName("input"): self.input})

    def sources(self) -> NodeSources:
        return NodeSources(sources={SourceName("created-payload"): self.created_payload})


S3PresignedUrl = NewType('S3PresignedUrl', str)

class WithS3PresignedUrl[Input](BaseModel):
    """
    this is ExecutorPayload generated by S3PresignedUrlCreator;
    it includes the original input and the generated S3 presigned URL
    This is what should end up sent to the executor
    """
    input: Input
    s3_presigned_url: S3PresignedUrl

class S3PresignedUrlCreator[Input](PayloadCreator[Input, WithS3PresignedUrl[Input]], ActorBuilder):
    s3_client_provider: S3ClientProvider
    presigned_url_expiration_seconds: int
    bucket: str

    def __init__(
        self,
        _id: str,
        *,
        bucket: str,
        s3_client_provider: S3ClientProvider = DEFAULT_S3_CLIENT_PROVIDER,
        presigned_url_expiration_seconds: int = 900,
    ) -> None:
        super().__init__(_id)
        assert presigned_url_expiration_seconds > 0, "presigned_url_expiration_seconds must be > 0"
        self.s3_client_provider = s3_client_provider
        self.presigned_url_expiration_seconds = presigned_url_expiration_seconds
        self.bucket = bucket

    def build_actor(self, *, pipe_to_bus: PipeToBus, context_store: ContextStore) -> Actor:
        return S3PresignedUrlCreatorActor[Input](spec=self, pipe_to_bus=pipe_to_bus, context_store=context_store)


class S3PresignedUrlCreatorActor[Input](Actor):
    spec: S3PresignedUrlCreator[Input]
    _s3_client: S3Client

    def __init__(
        self,
        *,
        spec: S3PresignedUrlCreator[Input],
        pipe_to_bus: PipeToBus,
        context_store: ContextStore,
    ) -> None:
        super().__init__(name=spec.id, pipe_to_bus=pipe_to_bus, context_store=context_store)
        self.spec = spec
        self._s3_client = self.spec.s3_client_provider.get_client()

    def handlers(self) -> dict[Sink[Any], EventHandler]:
        return {
            self.spec.input: self.add_presigned_url
        }

    def add_presigned_url(
        self,
        ctx: Context,
        event: ReceiveEvent[Input],
    ) -> MessagesToSend:
        s3_key = str(uuid.uuid7())
        ctx.set_user_data(str(self.spec.id), s3_key)

        url = self._s3_client.generate_presigned_url(
            ClientMethod="put_object",
            Params={"Bucket": self.spec.bucket, "Key": s3_key},
            ExpiresIn=self.spec.presigned_url_expiration_seconds,
            HttpMethod="PUT",
        )

        payload_for_executor = WithS3PresignedUrl(
            input=event.payload,
            s3_presigned_url=S3PresignedUrl(url),
        )


        return (
            SendEvent(
                ctx_id=event.ctx_id,
                source=self.spec.created_payload,
                payload=payload_for_executor,
            ),
        )
