import uuid
from typing import TYPE_CHECKING, NewType, override

from pydantic import BaseModel

from nexus.actors.s3_client_provider import DEFAULT_S3_CLIENT_PROVIDER, S3ClientProvider
from nexus.core.dsl.nodes import NodeSinks, NodeSources, Sink, SinkName, Source, SourceName, Transform
from nexus.core.runtime.actor import Actor, ActorBuilder
from nexus.core.runtime.actor_patterns import TransformActor
from nexus.core.runtime.context_store import Context, ContextStore
from nexus.core.runtime.events import PipeToBus
from nexus.utils.exceptions import ActorMisconfiguredException

if TYPE_CHECKING:
    from mypy_boto3_s3 import S3Client


class PayloadCreator[Input, ExecutorPayload](Transform[Input, ExecutorPayload]):
    input: Sink[Input]  # consumes attempts generated by retry strategy
    created_payload: Source[ExecutorPayload]  # emits the next attempt to execute,
    # with the original input and the generated payload for the executor

    def __init__(self, _id: str) -> None:
        super().__init__(_id)

        # aliases for convenience
        self.input = self.sink
        self.created_payload = self.ok

    def sinks(self) -> NodeSinks:
        return NodeSinks(sinks={SinkName("input"): self.input})

    def sources(self) -> NodeSources:
        return NodeSources(
            sources={SourceName("created-payload"): self.created_payload, SourceName("error"): self.error},
            default_source=self.created_payload,
        )


S3PresignedUrl = NewType("S3PresignedUrl", str)


class WithS3PresignedUrl[Input](BaseModel):
    """
    this is ExecutorPayload generated by S3PresignedUrlCreator;
    it includes the original input and the generated S3 presigned URL
    This is what should end up sent to the executor
    """

    input: Input
    s3_presigned_url: S3PresignedUrl


class S3PresignedUrlCreator[Input](PayloadCreator[Input, WithS3PresignedUrl[Input]], ActorBuilder):
    s3_client_provider: S3ClientProvider
    presigned_url_expiration_seconds: int
    bucket: str

    def __init__(
        self,
        _id: str,
        *,
        bucket: str,
        s3_client_provider: S3ClientProvider = DEFAULT_S3_CLIENT_PROVIDER,
        presigned_url_expiration_seconds: int = 900,
    ) -> None:
        super().__init__(_id)
        if presigned_url_expiration_seconds <= 0:
            raise ActorMisconfiguredException("presigned_url_expiration_seconds must be > 0")
        self.s3_client_provider = s3_client_provider
        self.presigned_url_expiration_seconds = presigned_url_expiration_seconds
        self.bucket = bucket

    def build_actor(self, *, pipe_to_bus: PipeToBus, context_store: ContextStore) -> Actor:
        return S3PresignedUrlCreatorActor[Input](spec=self, pipe_to_bus=pipe_to_bus, context_store=context_store)


class S3PresignedUrlCreatorActor[Input](TransformActor[Input, WithS3PresignedUrl[Input]]):
    creator_spec: S3PresignedUrlCreator[Input]
    _s3_client: S3Client

    def __init__(
        self,
        *,
        spec: S3PresignedUrlCreator[Input],
        pipe_to_bus: PipeToBus,
        context_store: ContextStore,
    ) -> None:
        super().__init__(spec=spec, pipe_to_bus=pipe_to_bus, context_store=context_store)
        self.creator_spec = spec
        self._s3_client = self.creator_spec.s3_client_provider.get_client()

    @override
    def _transform(self, ctx: Context, payload: Input) -> WithS3PresignedUrl[Input]:
        s3_key = str(uuid.uuid7())
        ctx.set_user_data(str(self.spec.id), s3_key)

        url = self._s3_client.generate_presigned_url(
            ClientMethod="put_object",
            Params={"Bucket": self.creator_spec.bucket, "Key": s3_key},
            ExpiresIn=self.creator_spec.presigned_url_expiration_seconds,
            HttpMethod="PUT",
        )

        return WithS3PresignedUrl(
            input=payload,
            s3_presigned_url=S3PresignedUrl(url),
        )
