import uuid
from typing import Any, NewType, Protocol, cast

import boto3
from botocore.config import Config
from pydantic import BaseModel

from nexus.actors.retry_strategy import Attempt
from nexus.actors.s3_config import S3Config
from nexus.core.dsl.nodes import Node, NodeSinks, NodeSources, Sink, SinkName, Source, SourceName
from nexus.core.runtime.actor import Actor, ActorBuilder, EventHandler
from nexus.core.runtime.context_store import Context, ContextStore
from nexus.core.runtime.events import PipeToBus, ReceiveEvent, SendEvent


class ExecutionRequestInfo[Input, ExecutorPayload](BaseModel):
    """
    Describes the output of a payload creator; it includes the original attempt
    and the payload generated in the payload creator itself
    """
    attempt: Attempt[Input]
    payload_for_executor: ExecutorPayload

class PayloadCreator[Input, ExecutorPayload](Node):
    input: Sink[Attempt[Input]] # consumes attempts generated by retry strategy

    created_payload: Source[ExecutionRequestInfo[Input, ExecutorPayload]] # emits the next attempt to execute,
    # with the original input and the generated payload for the executor

    def __init__(self, _id: str) -> None:
        super().__init__(_id)
        self.input = Sink[Attempt[Input]](f"{self.id}-input")
        self.created_payload = Source[ExecutionRequestInfo[Input, ExecutorPayload]](f"{self.id}-created-payload")

    def sinks(self) -> NodeSinks:
        return NodeSinks(sinks={SinkName("input"): self.input})

    def sources(self) -> NodeSources:
        return NodeSources(sources={SourceName("created-payload"): self.created_payload})


S3PresignedUrl = NewType('S3PresignedUrl', str)

class WithS3PresignedUrl[Input](BaseModel):
    """
    this is ExecutorPayload generated by S3PresignedUrlCreator;
    it includes the original input and the generated S3 presigned URL
    This is what should end up sent to the executor
    """
    original_input: Input
    s3_presigned_url: S3PresignedUrl

class S3PresignedUrlCreator[Input](PayloadCreator[Input, WithS3PresignedUrl[Input]], ActorBuilder):
    s3_config: S3Config
    presigned_url_expiration_seconds: int

    def __init__(
        self,
        _id: str,
        *,
        s3_config: S3Config,
        presigned_url_expiration_seconds: int = 900,
    ) -> None:
        super().__init__(_id)
        assert presigned_url_expiration_seconds > 0, "presigned_url_expiration_seconds must be > 0"
        self.s3_config = s3_config
        self.presigned_url_expiration_seconds = presigned_url_expiration_seconds

    def build_actor(self, *, pipe_to_bus: PipeToBus, context_store: ContextStore) -> Actor:
        return S3PresignedUrlCreatorActor[Input](spec=self, pipe_to_bus=pipe_to_bus, context_store=context_store)


class S3PresignedUrlCreatorActor[Input](Actor):
    class _PresigningClient(Protocol):
        """
        protocol for the boto3 S3 client method we use for type-checking purposes
        """
        def generate_presigned_url(
            self,
            *,
            ClientMethod: str,
            Params: dict[str, str],
            ExpiresIn: int,
            HttpMethod: str,
        ) -> str:
            ...

    spec: S3PresignedUrlCreator[Input]
    _s3_client: _PresigningClient

    def __init__(
        self,
        *,
        spec: S3PresignedUrlCreator[Input],
        pipe_to_bus: PipeToBus,
        context_store: ContextStore,
    ) -> None:
        super().__init__(name=spec.id, pipe_to_bus=pipe_to_bus, context_store=context_store)
        self.spec = spec
        self._s3_client = cast(
            S3PresignedUrlCreatorActor._PresigningClient,
            boto3.client(  # pyright: ignore[reportUnknownMemberType]
                "s3",
                aws_access_key_id=self.spec.s3_config.aws_access_key_id,
                aws_secret_access_key=self.spec.s3_config.aws_secret_access_key,
                region_name=self.spec.s3_config.region_name,
                endpoint_url=self.spec.s3_config.endpoint_url,
                config=Config(
                    signature_version="s3v4",
                    s3={"addressing_style": self.spec.s3_config.s3_addressing_style},
                ),
            ),
        )

    def handlers(self) -> dict[Sink[Any], EventHandler]:
        return {
            self.spec.input: self.add_presigned_url
        }

    def add_presigned_url(
        self,
        ctx: Context,
        event: ReceiveEvent[Attempt[Input]],
    ) -> tuple[SendEvent[ExecutionRequestInfo[Input, WithS3PresignedUrl[Input]]],]:
        s3_key = str(uuid.uuid7())
        ctx.set_user_data(str(self.spec.id), s3_key)

        url = self._s3_client.generate_presigned_url(
            ClientMethod="put_object",
            Params={"Bucket": self.spec.s3_config.bucket_name, "Key": s3_key},
            ExpiresIn=self.spec.presigned_url_expiration_seconds,
            HttpMethod="PUT",
        )

        payload_for_executor = WithS3PresignedUrl(
            original_input=event.payload.original_input,
            s3_presigned_url=S3PresignedUrl(url),
        )

        execution_request = ExecutionRequestInfo(
            attempt=event.payload,
            payload_for_executor=payload_for_executor,
        )

        return (
            SendEvent(
                ctx_id=event.ctx_id,
                source=self.spec.created_payload,
                payload=execution_request,
            ),
        )
